name: "Install dependencies using Poetry"
author: "@Steffo99"
description: "An action to install Python dependencies using Poetry."
branding:
  icon: "truck"
  color: "#008cdb"
  
outputs:
  pyenv:
    description: "The location of the created Python environment."
    value: ${{ steps.find.outputs.pyenv }}

runs:
  using: composite
  
  steps:
    - name: "Install dependencies using Poetry"
      run: poetry install --no-interaction
      shell: bash

    - name: "Find Poetry Python environment"
      id: "find"
      run: echo "::set-output name=pyenv::$(poetry env list --full-path | cut -f1 -d' ')/bin"
      shell: bash
